version: '3'

services:
  data-db:
    image: mysql:8
    hostname: data-db
    container_name: data-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=
    volumes:
      - ./data/mysql/user:/var/lib/mysql
      - ./conf/mysql/conf.d:/etc/mysql/conf.d
  data-rdb:
    image: redis:6-alpine
    hostname: cache-redis
    volumes:
      - ./data/redis/cache/:/data
      - ./conf/redis/cache/redis.conf:/etc/redis/redis.conf
    ports:
      - "6350:6379"
    command: [ "redis-server","/etc/redis/redis.conf" ]